on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string


jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.test }}

